# Stage 1
FROM node:20.11.1-alpine3.19 AS builder
WORKDIR /app
COPY . .
RUN npm install 
RUN npm run build

# Stage 2
FROM alpine:latest AS certs
WORKDIR /certs
COPY openssl.cnf /etc/ssl/openssl.cnf
RUN apk add --no-cache openssl && \
    openssl req -newkey rsa:4096 -x509 -sha256 -days 3650 -nodes \
    -out frontend.crt -keyout frontend.key -config /etc/ssl/openssl.cnf

# Stage 3
FROM nginx:1.16.0-alpine
COPY --from=builder /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=certs /certs/frontend.crt /etc/nginx/ssl/frontend.crt
COPY --from=certs /certs/frontend.key /etc/nginx/ssl/frontend.key

CMD ["nginx", "-g", "daemon off;"]
